### ISSUE TITLE
Packaged version 0.0.2 contains lots of unnecessary files

### ISSUE THREAD

**Issue by PetrGlad** [siscia/postgres-type#3]
Unnecessary files amount to about 40 Mb. Those are db/*, src/postgre_types/core.clj

**Comment by siscia** [comment]
So sorry that I didn't come back to you...

Those files are from the clojars repo, right ?

**Comment by PetrGlad** [comment]
Yep, from clojars.

**Comment by siscia** [comment]
:+1: Thanks, the new version should have fix the issue
