### ISSUE TITLE
jsonb

### ISSUE THREAD

**Issue by yogthos** [siscia/postgres-type#5]
might be an idea to allow setting the type for JSON, JSONB is more useful for querying data.

**Comment by siscia** [comment]
Sure, it does sound like an idea.

Actually we could rewrite a function as 

``` clojure
(defn- add-jsonx-type [type write-json read-json]
  (assert (or (= type "json") (= type "jsonb")))
  ... )
```

And finally:

``` clojure
(def add-json-type (partial add-jsonx-type "json"))

(def add-jsonb-type (partial add-jsonx-type "jsonb"))
```

It is the first idea that crossed my mind, if you have better suggestion feel free to share :)

Cheers

**Comment by siscia** [comment]
@yogthos I just push on clojars the version `0.0.4` which include the jsonb type do you have some application where you can try to use it ?

**Comment by siscia** [comment]
Forget to mention that the code is in the branch: [workOnJsonb](https://github.com/siscia/postgres-type/tree/workOnJsonb)

**Comment by yogthos** [comment]
I ended up just extending right in my code, one thing to consider is perhaps making this open to other types such as `citext`. I'm using that and `Jdbc4Array` in my project currently.

**Comment by siscia** [comment]
If you could try to update the library to the last version `0.0.4` and make sure that everything is behaving as expected it would be great.

I tested it with a very small case and it is not enough, IMHO.

**Comment by yogthos** [comment]
seems to work ;)

**Comment by siscia** [comment]
Wonderfull :)

**Comment by siscia** [comment]
@yogthos log post for the 0.0.4 release with your name ("yogthos") and link to your website, you don't mind right ?

**Comment by yogthos** [comment]
sure :)
